<template>
  <div class="loadingio-spinner-magnify-zf9ubtv6okj">
    <div class="ldio-s6cddso3jy">
      <div><div>
      <div></div>
      <div></div>
      </div></div>
    </div>
  </div>
</template>

<script>
export default {

}
</script>

<style>

@keyframes ldio-s6cddso3jy {
    0%    { transform: translate(2px,2px) }
   33.33% { transform: translate(102px,2px) }
   66.66% { transform: translate(42px,102px) }
  100%    { transform: translate(2px,2px) }
}


.ldio-s6cddso3jy > div {
  transform: scale(0.96);
  transform-origin: 100px 100px;
}

.ldio-s6cddso3jy > div > div {
  animation: ldio-s6cddso3jy 1s linear infinite;
  position: absolute
}

.ldio-s6cddso3jy > div > div div:nth-child(1) {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  border: 12px solid #85a2b6;
  background: #bbcedd
}

.ldio-s6cddso3jy > div > div div:nth-child(2) {
  width: 17px;
  height:  51px;
  transform: rotate(-45deg);
  background: #85a2b6;
  border-radius: 0 0 8px 8px;
  position: absolute;
  top: 68px;
  left: 85px
}
.loadingio-spinner-magnify-zf9ubtv6okj {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-s6cddso3jy {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-s6cddso3jy div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>