<template>
  <div class="loadingio-spinner-spinner-hdbpqj2nreq">
    <div class="ldio-oamgpqwyrt">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script>
export default {

}
</script>

<style>

@keyframes ldio-oamgpqwyrt {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-oamgpqwyrt div {
  left: 93px;
  top: 35px;
  position: absolute;
  animation: ldio-oamgpqwyrt linear 0.625s infinite;
  background: #85a2b6;
  width: 14px;
  height: 14px;
  border-radius: 5.88px / 5.88px;
  transform-origin: 7px 65px;
}.ldio-oamgpqwyrt div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.5965909090909091s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(2) {
  transform: rotate(16.363636363636363deg);
  animation-delay: -0.5681818181818181s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(3) {
  transform: rotate(32.72727272727273deg);
  animation-delay: -0.5397727272727272s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(4) {
  transform: rotate(49.09090909090909deg);
  animation-delay: -0.5113636363636364s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(5) {
  transform: rotate(65.45454545454545deg);
  animation-delay: -0.4829545454545454s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(6) {
  transform: rotate(81.81818181818181deg);
  animation-delay: -0.45454545454545453s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(7) {
  transform: rotate(98.18181818181819deg);
  animation-delay: -0.4261363636363636s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(8) {
  transform: rotate(114.54545454545455deg);
  animation-delay: -0.3977272727272727s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(9) {
  transform: rotate(130.9090909090909deg);
  animation-delay: -0.36931818181818177s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(10) {
  transform: rotate(147.27272727272728deg);
  animation-delay: -0.3409090909090909s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(11) {
  transform: rotate(163.63636363636363deg);
  animation-delay: -0.3125s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(12) {
  transform: rotate(180deg);
  animation-delay: -0.28409090909090906s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(13) {
  transform: rotate(196.36363636363637deg);
  animation-delay: -0.2556818181818182s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(14) {
  transform: rotate(212.72727272727272deg);
  animation-delay: -0.22727272727272727s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(15) {
  transform: rotate(229.0909090909091deg);
  animation-delay: -0.19886363636363635s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(16) {
  transform: rotate(245.45454545454547deg);
  animation-delay: -0.17045454545454544s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(17) {
  transform: rotate(261.8181818181818deg);
  animation-delay: -0.14204545454545453s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(18) {
  transform: rotate(278.1818181818182deg);
  animation-delay: -0.11363636363636363s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(19) {
  transform: rotate(294.54545454545456deg);
  animation-delay: -0.08522727272727272s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(20) {
  transform: rotate(310.90909090909093deg);
  animation-delay: -0.056818181818181816s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(21) {
  transform: rotate(327.27272727272725deg);
  animation-delay: -0.028409090909090908s;
  background: #85a2b6;
}.ldio-oamgpqwyrt div:nth-child(22) {
  transform: rotate(343.6363636363636deg);
  animation-delay: 0s;
  background: #85a2b6;
}
.loadingio-spinner-spinner-hdbpqj2nreq {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-oamgpqwyrt {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-oamgpqwyrt div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>