<template>
  <div class="loadingio-spinner-gear-uclr1rwpce8">
    <div class="ldio-xeyyriim0b7">
      <div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {

}
</script>

<style>

@keyframes ldio-xeyyriim0b7 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(22.5deg) }
  100% { transform: rotate(45deg) }
}
.ldio-xeyyriim0b7 > div {
  transform-origin: 100px 100px;
  animation: ldio-xeyyriim0b7 0.2s infinite linear;
}
.ldio-xeyyriim0b7 > div div {
    position: absolute;
    width: 22px;
    height: 152px;
    background: #85a2b6;
    left: 100px;
    top: 100px;
    transform: translate(-50%,-50%);
}
.ldio-xeyyriim0b7 > div div:nth-child(1) {
    width: 120px;
    height: 120px;
    border-radius: 50%;
}
.ldio-xeyyriim0b7 > div div:nth-child(6) {
    width: 80px;
    height: 80px;
    background: #f1f2f3;
    border-radius: 50%;
}.ldio-xeyyriim0b7 > div div:nth-child(3) {
  transform: translate(-50%,-50%) rotate(45deg)
}.ldio-xeyyriim0b7 > div div:nth-child(4) {
  transform: translate(-50%,-50%) rotate(90deg)
}.ldio-xeyyriim0b7 > div div:nth-child(5) {
  transform: translate(-50%,-50%) rotate(135deg)
}
.loadingio-spinner-gear-uclr1rwpce8 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-xeyyriim0b7 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-xeyyriim0b7 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>